/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
   darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "primary": "#ffffff",
                    "surface-container-low": "#151d1d",
                    "outline-variant": "#3a4a49",
                    "surface-bright": "#323b3b",
                    "outline": "#839493",
                    "on-primary-fixed-variant": "#004f4f",
                    "on-primary-fixed": "#002020",
                    "on-tertiary-fixed-variant": "#5700c9",
                    "surface-container-high": "#232c2b",
                    "primary-fixed-dim": "#00dddd",
                    "on-error": "#690005",
                    "surface-dim": "#0d1515",
                    "surface": "#0d1515",
                    "secondary-fixed-dim": "#ffabef",
                    "on-primary": "#003737",
                    "on-background": "#dbe4e3",
                    "inverse-surface": "#dbe4e3",
                    "on-tertiary": "#3c0090",
                    "error": "#ffb4ab",
                    "surface-variant": "#2e3636",
                    "secondary-container": "#f733eb",
                    "tertiary-fixed-dim": "#d1bcff",
                    "on-secondary-fixed-variant": "#82007d",
                    "on-surface": "#dbe4e3",
                    "tertiary-container": "#e9ddff",
                    "surface-container-highest": "#2e3636",
                    "primary-fixed": "#00fbfc",
                    "on-primary-container": "#007070",
                    "inverse-on-surface": "#293232",
                    "secondary-fixed": "#ffd7f3",
                    "tertiary": "#ffffff",
                    "surface-container-lowest": "#081010",
                    "on-tertiary-container": "#7829ff",
                    "surface-tint": "#00dddd",
                    "primary-container": "#00fbfc",
                    "on-secondary-fixed": "#390036",
                    "on-tertiary-fixed": "#23005b",
                    "on-secondary": "#5c0058",
                    "on-error-container": "#ffdad6",
                    "on-secondary-container": "#51004d",
                    "surface-container": "#192121",
                    "background": "#0d1515",
                    "inverse-primary": "#006a6a",
                    "secondary": "#f733eb",
                    "tertiary-fixed": "#e9ddff",
                    "error-container": "#93000a",
                    "on-surface-variant": "#b9cac9"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "gutter": "24px",
                    "stack-xl": "160px",
                    "stack-md": "40px",
                    "stack-lg": "80px",
                    "margin-desktop": "64px",
                    "container-max": "1280px",
                    "margin-mobile": "24px"
            },
            "fontFamily": {
                    "section-title": ["Sora"],
                    "h3": ["Sora"],
                    "label-caps": ["Inter"],
                    "body-md": ["Inter"],
                    "body-lg": ["Inter"],
                    "code": ["Inter"],
                    "section-title-mobile": ["Sora"],
                    "hero-display": ["Sora"],
                    "hero-display-mobile": ["Sora"]
            },
            "fontSize": {
                    "section-title": ["56px", {"lineHeight": "120%", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                    "h3": ["32px", {"lineHeight": "140%", "fontWeight": "600"}],
                    "label-caps": ["14px", {"lineHeight": "100%", "letterSpacing": "0.1em", "fontWeight": "600"}],
                    "body-md": ["16px", {"lineHeight": "160%", "fontWeight": "400"}],
                    "body-lg": ["18px", {"lineHeight": "160%", "fontWeight": "400"}],
                    "code": ["14px", {"lineHeight": "150%", "fontWeight": "400"}],
                    "section-title-mobile": ["32px", {"lineHeight": "120%", "fontWeight": "600"}],
                    "hero-display": ["96px", {"lineHeight": "100%", "letterSpacing": "-0.04em", "fontWeight": "700"}],
                    "hero-display-mobile": ["48px", {"lineHeight": "110%", "letterSpacing": "-0.02em", "fontWeight": "700"}]
            }
          },
        },
      }

